const fs = require('fs');

const translations = {
    // Lesson 1 Exercises
    "'Greeting Matching'": "'अभिवादन मिलान'",
    "'Match the correct greeting with its situation'": "'इसकी स्थिति के साथ सही अभिवादन का मिलान करें'",
    "'Basic Phrases Practice'": "'बुनियादी वाक्यांश अभ्यास'",
    "'Select the appropriate phrase for each situation'": "'प्रत्येक स्थिति के लिए उपयुक्त वाक्यांश चुनें'",
    "'Thank You Expressions'": "'धन्यवाद की अभिव्यक्ति'",
    "'Learn different ways to express gratitude in Hindi'": "'हिंदी में आभार व्यक्त करने के विभिन्न तरीके सीखें'",
    // Lesson 2 Exercises
    "'Number Recognition'": "'संख्या पहचान'",
    "'Match Hindi numbers with their values'": "'हिंदी संख्याओं का उनके मान के साथ मिलान करें'",
    "'Counting Sequence'": "'गिनती का क्रम'",
    "'Fill in the missing numbers in the sequence'": "'अनुक्रम में छूटी हुई संख्याएँ भरें'",
    "'Number Writing Challenge'": "'संख्या लेखन चुनौती'",
    "'Write numbers in Hindi from 1 to 20'": "'हिंदी में 1 से 20 तक संख्याएँ लिखें'",
    // Lesson 3 Exercises
    "'Family Member Identification'": "'परिवार के सदस्यों की पहचान'",
    "'Identify family members and their relationships'": "'परिवार के सदस्यों और उनके रिश्तों को पहचानें'",
    "'Relationship Mapping'": "'रिश्ते का मिलान'",
    "'Match family members with Hindi terms'": "'परिवार के सदस्यों का हिंदी शब्दों के साथ मिलान करें'",
    "'Family Vocabulary Quiz'": "'पारिवारिक शब्दावली प्रश्नोत्तरी'",
    "'Test your knowledge of family-related words'": "'परिवार से संबंधित शब्दों के अपने ज्ञान का परीक्षण करें'",
    // Lesson 4 Exercises
    "'Food Item Recognition'": "'खाद्य पदार्थों की पहचान'",
    "'Identify common Indian food items'": "'सामान्य भारतीय खाद्य पदार्थों को पहचानें'",
    "'Restaurant Ordering'": "'रेस्तरां में ऑर्डर करना'",
    "'Practice ordering food at a restaurant'": "'रेस्तरां में खाना ऑर्डर करने का अभ्यास करें'",
    "'Food Preferences Quiz'": "'भोजन प्राथमिकता प्रश्नोत्तरी'",
    "'Talk about your favorite foods in Hindi'": "'हिंदी में अपने पसंदीदा भोजन के बारे में बात करें'",
    // Lesson 5 Exercises
    "'Daily Routine Sequencing'": "'दिनचर्या अनुक्रमण'",
    "'Arrange daily activities in correct order'": "'दैनिक गतिविधियों को सही क्रम में व्यवस्थित करें'",
    "'Activity Identification'": "'गतिविधि की पहचान'",
    "'Match activities with their descriptions'": "'गतिविधियों का उनके विवरण के साथ मिलान करें'",
    "'Morning Routine Building'": "'सुबह की दिनचर्या बनाना'",
    "'Build your morning routine in Hindi'": "'हिंदी में अपनी सुबह की दिनचर्या बनाएं'",
    // Lesson 6 Exercises
    "'Scaffolding Basics'": "'स्कैफोल्डिंग के मूल तत्व'",
    "'Understand the core concept of scaffolding'": "'स्कैफोल्डिंग की मूल अवधारणा को समझें'",
    "'Support Types'": "'समर्थन के प्रकार'",
    "'Identify different ways to support learning'": "'सीखने में मदद करने के विभिन्न तरीकों को पहचानें'",
    "'Growth Mindset'": "'विकास की मानसिकता'",
    "'Learn how challenges help you grow'": "'जानें कि चुनौतियां आपको कैसे आगे बढ़ाती हैं'",

    // Prompts and Hints
    "'What does नमस्ते mean?'": "'नमस्ते का क्या अर्थ है?'",
    "'A common way to greet someone'": "'किसी का अभिवादन करने का सामान्य तरीका'",
    "'When do you say सुप्रभात?'": "'आप सुप्रभात कब कहते हैं?'",
    "'Hint: It is used in the morning'": "'संकेत: यह सुबह उपयोग किया जाता है'",
    "'Which is a formal greeting?'": "'औपचारिक अभिवादन कौन सा है?'",
    "'Hint: More formal than नमस्ते'": "'संकेत: नमस्ते से अधिक औपचारिक'",
    "'How do you say goodbye in Hindi?'": "'आप हिंदी में अलविदा कैसे कहते हैं?'",
    "'Hint: Similar to hello'": "'संकेत: नमस्ते के समान'",

    "'What to say when meeting someone for the first time?'": "'पहली बार किसी से मिलने पर क्या कहें?'",
    "'Express your happiness at meeting them'": "'उनसे मिलकर अपनी खुशी व्यक्त करें'",
    "'How to respond to a greeting?'": "'अभिवादन का उत्तर कैसे दें?'",
    "'Greet them back respectfully'": "'सम्मानपूर्वक वापस अभिवादन करें'",
    "'What is a polite way to ask for something?'": "'कुछ माँगने का विनम्र तरीका क्या है?'",
    "'Use the word please'": "'कृपया शब्द का प्रयोग करें'",
    "'How to introduce yourself?'": "'अपना परिचय कैसे दें?'",
    "'State your name and express pleasure'": "'अपना नाम बताएं और खुशी व्यक्त करें'",

    "'What is the most common way to say thank you?'": "'धन्यवाद कहने का सबसे आम तरीका क्या है?'",
    "'Hint: Two similar words'": "'संकेत: दो समान शब्द'",
    "'An informal way to express gratitude?'": "'आभार व्यक्त करने का अनौपचारिक तरीका?'",
    "'Hint: Often used in casual settings'": "'संकेत: अक्सर अनौपचारिक सेटिंग्स में उपयोग किया जाता है'",
    "'What does खुशी mean?'": "'खुशी का क्या अर्थ है?'",
    "'Hint: A positive emotion'": "'संकेत: एक सकारात्मक भावना'",
    "'How do you politely respond to thanks?'": "'आप धन्यवाद का विनम्रतापूर्वक उत्तर कैसे देते हैं?'",
    "'Hint: Means you are welcome'": "'संकेत: इसका मतलब है आपका स्वागत है'",

    "'What is the Hindi word for number 1?'": "'संख्या 1 के लिए हिंदी शब्द क्या है?'",
    "'First number in sequence'": "'अनुक्रम में पहली संख्या'",
    "'How do you say 5 in Hindi?'": "'हिंदी में 5 को कैसे कहते हैं?'",
    "'Midpoint of 1-10'": "'1-10 का मध्य बिंदु'",
    "'What is 10 called in Hindi?'": "'हिंदी में 10 को क्या कहा जाता है?'",
    "'The complete first sequence'": "'पूरा पहला अनुक्रम'",
    "'How do you say 20 in Hindi?'": "'हिंदी में 20 को कैसे कहते हैं?'",
    "'Double the number 10'": "'संख्या 10 का दोगुना'",

    "'Complete the sequence: 1, 2, 3, ___, 5'": "'अनुक्रम पूरा करें: 1, 2, 3, ___, 5'",
    "'The fourth number'": "'चौथी संख्या'",
    "'What comes after 7?'": "'7 के बाद क्या आता है?'",
    "'Hint: 7 + 1 = ?'": "'संकेत: 7 + 1 = ?'",
    "'Fill in: ___, 6, 7, 8, ___'": "'भरें: ___, 6, 7, 8, ___'",
    "'Consecutive numbers'": "'लगातार संख्याएँ'",

    "'What is 15 in Hindi?'": "'हिंदी में 15 क्या है?'",
    "'Hint: 10 + 5 = पंद्रह'": "'संकेत: 10 + 5 = पंद्रह'",
    "'How do you write 25 in Hindi?'": "'हिंदी में 25 कैसे लिखते हैं?'",
    "'Hint: 20 + 5 = पच्चीस'": "'संकेत: 20 + 5 = पच्चीस'",
    "'What is 100 in Hindi?'": "'हिंदी में 100 क्या है?'",
    "'The biggest number in this lesson'": "'इस पाठ की सबसे बड़ी संख्या'",

    "'Who is your mother''s mother?'": "'आपकी माँ की माँ कौन है?'",
    "'Hint: Grand + Mother'": "'संकेत: नानी'",
    "'What do you call your father''s male sibling?'": "'आप अपने पिता के भाई को क्या कहते हैं?'",
    "'Hint: Uncle in English'": "'संकेत: अंग्रेजी में अंकल'",
    "'Who is your father''s wife?'": "'आपके पिता की पत्नी कौन है?'",
    "'Hint: Female parent'": "'संकेत: महिला अभिभावक (माँ)'",
    "'What is a word for brother in Hindi?'": "'हिंदी में भाई के लिए शब्द क्या है?'",
    "'Hint: Common family term'": "'संकेत: सामान्य पारिवारिक शब्द'",

    "'Match: माता'": "'मिलान करें: माता'",
    "'Hint: Mother related'": "'संकेत: माँ से संबंधित'",
    "'Match: भैया'": "'मिलान करें: भैया'",
    "'Hint: Brother related'": "'संकेत: भाई से संबंधित'",
    "'Match: नानी'": "'मिलान करें: नानी'",
    "'Hint: Grandmother (maternal)'": "'संकेत: नानी (मातृ)'",

    "'What does परिवार mean?'": "'परिवार का क्या अर्थ है?'",
    "'All relatives together'": "'सभी रिश्तेदार एक साथ'",
    "'How do you say \"my sister\" in Hindi?'": "'आप हिंदी में \"मेरी बहन\" कैसे कहते हैं?'",
    "'Possessive form of बहन'": "'बहन का अधिकारवाचक रूप'",
    "'Who are your पिता''s parents?'": "'आपके पिता के माता-पिता कौन हैं?'",
    "'Paternal grandparents'": "'पिता पक्ष के दादा-दादी'",

    "'What is रोटी?'": "'रोटी क्या है?'",
    "'Hint: Flatbread made from wheat'": "'संकेत: गेहूं से बनी चपटी रोटी'",
    "'What is दाल?'": "'दाल क्या है?'",
    "'Hint: Protein source, made from lentils'": "'संकेत: प्रोटीन का स्रोत, दाल से बना है'",
    "'What is a famous Indian rice dish?'": "'एक प्रसिद्ध भारतीय चावल का व्यंजन क्या है?'",
    "'Hint: Biryani'": "'संकेत: बिरयानी'",
    "'What is essential to drink with meals?'": "'भोजन के साथ पीने के लिए क्या आवश्यक है?'",
    "'Hint: Water'": "'संकेत: पानी'",

    "'How do you ask for food at a restaurant?'": "'रेस्तरां में खाना कैसे मांगते हैं?'",
    "'Hint: Use माँगना (to ask for)'": "'संकेत: माँगना का प्रयोग करें'",
    "'What do you say to order water?'": "'पानी ऑर्डर करने के लिए आप क्या कहते हैं?'",
    "'Hint: Polite request'": "'संकेत: विनम्र अनुरोध'",
    "'How to ask for rice in Hindi?'": "'हिंदी में चावल कैसे मांगें?'",
    "'Hint: चावल please'": "'संकेत: कृपया चावल'",

    "'What does खाना mean?'": "'खाना का क्या अर्थ है?'",
    "'Hint: Basic necessity'": "'संकेत: बुनियादी जरूरत'",
    "'Where do you go to eat?'": "'आप खाने के लिए कहाँ जाते हैं?'",
    "'Hint: Restaurant'": "'संकेत: रेस्तरां'",
    "'What is सब्जी?'": "'सब्जी क्या है?'",
    "'Hint: Plant-based food component'": "'संकेत: पौधे आधारित भोजन'",

    "'What do you do first in the morning?'": "'आप सुबह सबसे पहले क्या करते हैं?'",
    "'Hint: Opening your eyes'": "'संकेत: अपनी आँखें खोलना'",
    "'What comes after waking up?'": "'उठने के बाद क्या आता है?'",
    "'Hint: Personal hygiene'": "'संकेत: व्यक्तिगत स्वच्छता'",
    "'What do you do after bathing?'": "'नहाने के बाद आप क्या करते हैं?'",
    "'Hint: First meal of the day'": "'संकेत: दिन का पहला भोजन'",
    "'What is the last activity of the day?'": "'दिन की आखिरी गतिविधि क्या है?'",
    "'Hint: Rest at night'": "'संकेत: रात में आराम करना'",

    "'What does पढ़ाई करना mean?'": "'पढ़ाई करना का क्या अर्थ है?'",
    "'Hint: Educational activity'": "'संकेत: शैक्षिक गतिविधि'",
    "'What is काम?'": "'काम क्या है?'",
    "'Hint: Professional responsibility'": "'संकेत: व्यावसायिक जिम्मेदारी'",
    "'What does दिनचर्या mean?'": "'दिनचर्या का क्या अर्थ है?'",
    "'Hint: Daily schedule'": "'संकेत: दैनिक कार्यक्रम'",

    "'How do you describe waking up early?'": "'आप जल्दी उठने का वर्णन कैसे करते हैं?'",
    "'Hint: जल्दी उठना'": "'संकेत: जल्दी उठना'",
    "'What is important for cleanliness?'": "'स्वच्छता के लिए क्या महत्वपूर्ण है?'",
    "'Hint: Bathing'": "'संकेत: नहाना'",
    "'Why is breakfast important?'": "'नाश्ता क्यों महत्वपूर्ण है?'",
    "'Hint: Starts the day with energy'": "'संकेत: दिन की शुरुआत ऊर्जा से करता है'",

    "'What is scaffolding like?'": "'स्कैफोल्डिंग किस की तरह है?'",
    "'Hint: Think of a building'": "'संकेत: एक इमारत के बारे में सोचें'",
    "'What happens to support over time?'": "'समय के साथ समर्थन का क्या होता है?'",
    "'Hint: It changes'": "'संकेत: यह बदलता है'",
    "'Why do we use scaffolding?'": "'हम स्कैफोल्डिंग का उपयोग क्यों करते हैं?'",
    "'Hint: To help learning'": "'संकेत: सीखने में मदद के लिए'",

    "'Which is a visual support?'": "'दृश्य समर्थन कौन सा है?'",
    "'Hint: Something you see'": "'संकेत: कुछ ऐसा जो आप देखते हैं'",
    "'Which is a verbal support?'": "'मौखिक समर्थन कौन सा है?'",
    "'Hint: Something you hear'": "'संकेत: कुछ ऐसा जो आप सुनते हैं'",
    "'Which is a social support?'": "'सामाजिक समर्थन कौन सा है?'",
    "'Hint: Involving people'": "'संकेत: लोगों को शामिल करना'",

    "'Mistakes are...'": "'गलतियाँ हैं...'",
    "'Hint: Positive view'": "'संकेत: सकारात्मक दृष्टिकोण'",
    "'If I find it hard, I should...'": "'अगर मुझे यह कठिन लगता है, तो मुझे चाहिए...'",
    "'Hint: Don''t stop'": "'संकेत: रुकें नहीं'",
    "'My brain grows when I...'": "'मेरा दिमाग बढ़ता है जब मैं...'",
    "'Hint: Challenge'": "'संकेत: चुनौती'",

    // Options Translation
    "'Father'": "'पिता'",
    "'Food'": "'खाना'",
    "'Hello/Goodbye'": "'नमस्ते/अलविदा'",
    "'Thank you'": "'धन्यवाद'",
    "'At noon'": "'दोपहर में'",
    "'In the morning'": "'सुबह में'",
    "'At night'": "'रात में'",
    "'Anytime'": "'किसी भी समय'",
    "'Sadness'": "'उदासी'",
    "'Happiness'": "'खुशी'",
    "'Anger'": "'क्रोध'",
    "'Fear'": "'डर'",
    "'Mother'": "'माता'",
    "'Sister'": "'बहन'",
    "'Grandmother'": "'दादी/नानी'",
    "'Younger Brother'": "'छोटा भाई'",
    "'Older Brother'": "'बड़ा भाई'",
    "'Uncle'": "'चाचा'",
    "'Grandfather'": "'दादा / नाना'",
    "'Paternal Grandmother'": "'दादी'",
    "'Maternal Grandmother'": "'नानी'",
    "'Paternal Grandfather'": "'दादा'",
    "'Maternal Grandfather'": "'नाना'",
    "'Friends'": "'दोस्त'",
    "'Family'": "'परिवार'",
    "'Neighbors'": "'पड़ोसी'",
    "'Teachers'": "'शिक्षक'",
    "'Rice'": "'चावल'",
    "'Flatbread'": "'रोटी'",
    "'Meat'": "'मांस'",
    "'Bread'": "'ब्रेड'",
    "'Lentils'": "'दाल'",
    "'Vegetables'": "'सब्जियां'",
    "'Fruits'": "'फल'",
    "'Water'": "'पानी'",
    "'School'": "'स्कूल'",
    "'Home'": "'घर'",
    "'Restaurant'": "'रेस्तरां'",
    "'Park'": "'पार्क'",
    "'Working'": "'काम करना'",
    "'Studying'": "'पढ़ाई करना'",
    "'Playing'": "'खेलना'",
    "'Sleeping'": "'सोना'",
    "'Job/Work'": "'काम / नौकरी'",
    "'Play'": "'खेल'",
    "'Daily Schedule'": "'दैनिक कार्यक्रम'",
    "'Daily Routine'": "'दिनचर्या'",

    "'A Support Structure'": "'एक समर्थन संरचना'",
    "'A Race Car'": "'एक रेस कार'",
    "'A Wall'": "'एक दीवार'",
    "'A Trap'": "'एक जाल'",
    "'It increases'": "'यह बढ़ता है'",
    "'It decreases (fades)'": "'यह कम होता है (घटता है)'",
    "'It stays the same'": "'यह वैसा ही रहता है'",
    "'It stops'": "'यह रुक जाता है'",
    "'To make it harder'": "'इसे कठिन बनाने के लिए'",
    "'To make it easier'": "'इसे आसान बनाने के लिए'",
    "'To confuse you'": "'आपको भ्रमित करने के लिए'",
    "'To waste time'": "'समय बर्बाद करने के लिए'",

    "'Pictures/Diagrams'": "'चित्र/आरेख'",
    "'Talking'": "'बात करना'",
    "'Running'": "'दौड़ना'",
    "'Explanations'": "'स्पष्टीकरण'",
    "'Images'": "'चित्र'",
    "'Gestures'": "'इशारे'",
    "'Silence'": "'मौन'",
    "'Working with a friend'": "'एक दोस्त के साथ काम करना'",
    "'Working alone'": "'अकेले काम करना'",
    "'Ignoring others'": "'दूसरों को अनदेखा करना'",

    "'Opportunities to learn'": "'सीखने के अवसर'",
    "'Bad things'": "'बुरी चीजें'",
    "'Failures'": "'विफलताएं'",
    "'Scary'": "'डरावना'",
    "'Keep trying'": "'कोशिश करते रहें'",
    "'Give up'": "'हार मान लें'",
    "'Cry'": "'रोएं'",
    "'Get angry'": "'क्रोधित हों'",
    "'Face challenges'": "'चुनौतियों का सामना करता हूँ'",
    "'Do nothing'": "'कुछ नहीं करता'",
    "'Watch TV'": "'टीवी देखता हूँ'",
    "'Sleep'": "'सोता हूँ'"
};

let sql = fs.readFileSync('server/sql/seed-data.sql', 'utf8');

for (const [eng, hin] of Object.entries(translations)) {
    sql = sql.split(eng).join(hin);
}

fs.writeFileSync('server/sql/seed-data.sql', sql);
console.log('Successfully translated English inserts to Hindi in seed-data.sql');
